/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package translator;

import static java.awt.SystemColor.text;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import translator.Controller.*;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.TransferHandler;
import javax.swing.text.Keymap;

/**
 *
 * @author anhinox
 */
public class Translator extends javax.swing.JFrame
{

    /**
     * Creates new form TeencodeTranslator
     */
    private Converter conv = new Converter();

    public Translator()
    {
        initComponents();
        teencodeTextArea.addKeyListener(new KeyAdapter()
        {
            @Override
            public void keyTyped(KeyEvent e)
            {
                //when space bar is pressed (or back space) do the conversion
                if (Character.isWhitespace(e.getKeyChar()) || e.getKeyCode() == KeyEvent.VK_BACK_SPACE)
                {
                    vietnameseTextArea.setText(conv.TeencodeToVietnamese(teencodeTextArea.getText()));
                }
            }
        });

        vietnameseTextArea.addKeyListener(new KeyAdapter()
        {
            @Override
            public void keyTyped(KeyEvent e)
            {
                //when space bar is pressed (or back space) do the conversion
                if (Character.isWhitespace(e.getKeyChar()) || e.getKeyCode() == KeyEvent.VK_BACK_SPACE)
                {
                    teencodeTextArea.setText(conv.VietnameseToTeencode(vietnameseTextArea.getText()));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        englishTextLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teencodeTextArea = new javax.swing.JTextArea();
        InputTextLabel = new javax.swing.JLabel();
        clearTeencodeText = new javax.swing.JButton();
        readTcText = new javax.swing.JButton();
        copyTcText = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        headerLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vietnameseTextArea = new javax.swing.JTextArea();
        outputTextLabel = new javax.swing.JLabel();
        clearVNText = new javax.swing.JButton();
        readVnText = new javax.swing.JButton();
        copyVnText = new javax.swing.JButton();
        translateVnToTc = new javax.swing.JButton();
        translateTcToVn = new javax.swing.JButton();

        englishTextLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        englishTextLabel2.setForeground(new java.awt.Color(255, 255, 255));
        englishTextLabel2.setText(" FROM THIS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 121, 107));

        jPanel2.setBackground(new java.awt.Color(0, 150, 136));
        jPanel2.setPreferredSize(new java.awt.Dimension(840, 324));

        teencodeTextArea.setColumns(20);
        teencodeTextArea.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        teencodeTextArea.setRows(5);
        jScrollPane1.setViewportView(teencodeTextArea);

        InputTextLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        InputTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        InputTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputTextLabel.setText("TEENCODE");

        clearTeencodeText.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        clearTeencodeText.setForeground(new java.awt.Color(0, 51, 51));
        clearTeencodeText.setText("X");
        clearTeencodeText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearTeencodeTextActionPerformed(evt);
            }
        });

        readTcText.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        readTcText.setForeground(new java.awt.Color(0, 51, 51));
        readTcText.setText("R");
        readTcText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                readTcTextActionPerformed(evt);
            }
        });

        copyTcText.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        copyTcText.setForeground(new java.awt.Color(0, 51, 51));
        copyTcText.setText("C");
        copyTcText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                copyTcTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(InputTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearTeencodeText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(readTcText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(copyTcText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clearTeencodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(readTcText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(copyTcText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        headerLabel1.setBackground(new java.awt.Color(255, 255, 255));
        headerLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        headerLabel1.setForeground(new java.awt.Color(0, 204, 102));
        headerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel1.setText("T33NC0D3 TR4NSL4T0R");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(headerLabel1)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 150, 136));
        jPanel3.setPreferredSize(new java.awt.Dimension(840, 324));

        vietnameseTextArea.setColumns(20);
        vietnameseTextArea.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        vietnameseTextArea.setRows(5);
        jScrollPane2.setViewportView(vietnameseTextArea);

        outputTextLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        outputTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        outputTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputTextLabel.setText("VIETNAMESE");

        clearVNText.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        clearVNText.setForeground(new java.awt.Color(0, 51, 51));
        clearVNText.setText("X");
        clearVNText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearVNTextActionPerformed(evt);
            }
        });

        readVnText.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        readVnText.setForeground(new java.awt.Color(0, 51, 51));
        readVnText.setText("R");
        readVnText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                readVnTextActionPerformed(evt);
            }
        });

        copyVnText.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        copyVnText.setForeground(new java.awt.Color(0, 51, 51));
        copyVnText.setText("C");
        copyVnText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                copyVnTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearVNText)
                    .addComponent(readVnText)
                    .addComponent(copyVnText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(clearVNText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(readVnText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(copyVnText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        translateVnToTc.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        translateVnToTc.setForeground(new java.awt.Color(0, 51, 51));
        translateVnToTc.setText("<<<");
        translateVnToTc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                translateVnToTcActionPerformed(evt);
            }
        });

        translateTcToVn.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        translateTcToVn.setForeground(new java.awt.Color(0, 51, 51));
        translateTcToVn.setText(">>>");
        translateTcToVn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                translateTcToVnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(translateVnToTc)
                    .addComponent(translateTcToVn))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(translateVnToTc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(translateTcToVn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearTeencodeTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearTeencodeTextActionPerformed
    {//GEN-HEADEREND:event_clearTeencodeTextActionPerformed
        // TODO add your handling code here:
        clearTeencodeText.addActionListener((e)
                ->
        {
            teencodeTextArea.setText(null);
        });
    }//GEN-LAST:event_clearTeencodeTextActionPerformed

    private void clearVNTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearVNTextActionPerformed
    {//GEN-HEADEREND:event_clearVNTextActionPerformed
        // TODO add your handling code here:
        clearVNText.addActionListener((e)
                ->
        {
            vietnameseTextArea.setText(null);
        });
    }//GEN-LAST:event_clearVNTextActionPerformed

    private void translateVnToTcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_translateVnToTcActionPerformed
    {//GEN-HEADEREND:event_translateVnToTcActionPerformed
        // TODO add your handling code here:
        teencodeTextArea.setText(conv.VietnameseToTeencode(vietnameseTextArea.getText()));
    }//GEN-LAST:event_translateVnToTcActionPerformed

    private void translateTcToVnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_translateTcToVnActionPerformed
    {//GEN-HEADEREND:event_translateTcToVnActionPerformed
        // TODO add your handling code here:
        vietnameseTextArea.setText(conv.TeencodeToVietnamese(teencodeTextArea.getText()));
    }//GEN-LAST:event_translateTcToVnActionPerformed

    private void readTcTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_readTcTextActionPerformed
    {//GEN-HEADEREND:event_readTcTextActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        try
        {
            FileReader reader = new FileReader(filename);
            BufferedReader br = new BufferedReader(reader);
            teencodeTextArea.read(br, null);
            br.close();
            teencodeTextArea.requestFocus();

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_readTcTextActionPerformed

    private void copyTcTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_copyTcTextActionPerformed
    {//GEN-HEADEREND:event_copyTcTextActionPerformed
        // TODO add your handling code here:
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection selection = new StringSelection(teencodeTextArea.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_copyTcTextActionPerformed

    private void readVnTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_readVnTextActionPerformed
    {//GEN-HEADEREND:event_readVnTextActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        try
        {
            FileReader reader = new FileReader(filename);
            BufferedReader br = new BufferedReader(reader);
            vietnameseTextArea.read(br, null);
            br.close();
            vietnameseTextArea.requestFocus();

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_readVnTextActionPerformed

    private void copyVnTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_copyVnTextActionPerformed
    {//GEN-HEADEREND:event_copyVnTextActionPerformed
        // TODO add your handling code here:
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection selection = new StringSelection(vietnameseTextArea.getText());
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_copyVnTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Translator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Translator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Translator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Translator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Translator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InputTextLabel;
    private javax.swing.JButton clearTeencodeText;
    private javax.swing.JButton clearVNText;
    private javax.swing.JButton copyTcText;
    private javax.swing.JButton copyVnText;
    private javax.swing.JLabel englishTextLabel2;
    private javax.swing.JLabel headerLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel outputTextLabel;
    private javax.swing.JButton readTcText;
    private javax.swing.JButton readVnText;
    private javax.swing.JTextArea teencodeTextArea;
    private javax.swing.JButton translateTcToVn;
    private javax.swing.JButton translateVnToTc;
    private javax.swing.JTextArea vietnameseTextArea;
    // End of variables declaration//GEN-END:variables
}
